FROM ruby:4.0.5

RUN apt-get update -qq && \
    apt-get install -y build-essential nodejs sqlite3 libsqlite3-dev

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bash", "-c", "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"]