version: "3.9"

services:
  db:
    image: postgres:17
    container_name: student_management_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
      POSTGRES_DB: student_management_development

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: student_management_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

  web:
    build: .

    container_name: student_management_app

    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:prepare &&
      bundle exec rails server -b 0.0.0.0
      "

    ports:
      - "3000:3000"

    volumes:
      - .:/app

    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
      REDIS_URL: redis://redis:6379/0

    depends_on:
      - db
      - redis

  sidekiq:
    build: .

    container_name: student_management_sidekiq

    command: bundle exec sidekiq

    volumes:
      - .:/app

    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
      REDIS_URL: redis://redis:6379/0

    depends_on:
      - db
      - redis

volumes:
  postgres_data: