default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: student_management_app
  host: 127.0.0.1
  username: postgres
  password: post123
  port: 5432

test:
  <<: *default
  database: student_management_test
  host: 127.0.0.1
  username: postgres
  password: post123
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> 